# Automatically generated by pip2arch on 2015-10-02
# Maintainer: Sebastian Neef <aur AT gehaxelt DOT IN>

pkgname=python-ipy
pkgver=0.83
pkgrel=1
pkgdesc="Class and tools for handling of IPv4 and IPv6 addresses and networks"
url="https://github.com/autocracy/python-ipy"
depends=('python' )
makedepends=('python3' )
license=('CUSTOM')
arch=('any')
source=('https://pypi.python.org/packages/source/I/IPy/IPy-0.83.tar.gz')
md5sums=('7b8c6eb4111b15aea31b67108e769712')

build() {
    cd $srcdir/IPy-0.83
    python setup.py build
}

package() {
    cd $srcdir/IPy-0.83
    python setup.py install --root="$pkgdir" --optimize=1 
}
